version: '3.9'

networks:
  shelter-network:
    driver: bridge

services:
  shelter-service-db:
    container_name: shelter-service-db
    image: postgres
    networks:
      - shelter-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: shelter-api
    image: spring-boot-api-shelter-img
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - shelter-network
    depends_on:
      - shelter-service-db
    ports:
      - 8080:8080
    restart: always

volumes:
  pgdata: {}