version: '3.9'

services:
  shelter_service_db:
    container_name: shelter_service_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

#  api:
#    container_name: shelter-api
#    image: spring-boot-api-shelter-img
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - shelter_service_db
#    ports:
#      - 8080:8080
#    restart: always

volumes:
  pgdata: {}